#include <inttypes.h>

#ifndef INC_CPU_INTERFACE_H_
#define INC_CPU_INTERFACE_H_
class CPU_INTERFACE
{
public:
	enum Interrupt {
		USER_SOFTWARE_INTERRUPT_INTERRUPT_CAUSE,
		SUPERVISOR_SOFTWARE_INTERRUPT_INTERRUPT_CAUSE,
		//RESERVED_FOR_FUTURE_STANDARD_USE_INTERRUPT_CAUSE,
		MACHINE_SOFTWARE_INTERRUPT_INTERRUPT_CAUSE = 3,
		USER_TIMER_INTERRUPT_INTERRUPT_CAUSE,
		SUPERVISOR_TIMER_INTERRUPT_INTERRUPT_CAUSE,
		//RESERVED_FOR_FUTURE_STANDARD_USE_INTERRUPT_CAUSE,
		MACHINE_TIMER_INTERRUPT_INTERRUPT_CAUSE = 7,
		USER_EXTERNAL_INTERRUPT_INTERRUPT_CAUSE,
		SUPERVISOR_EXTERNAL_INTERRUPT_INTERRUPT_CAUSE,
		//RESERVED_FOR_FUTURE_STANDARD_USE_INTERRUPT_CAUSE,
		MACHINE_EXTERNAL_INTERRUPT_INTERRUPT_CAUSE = 11,
		//RESERVED_FOR_FUTURE_STANDARD_USE_INTERRUPT_CAUSE,
		//RESERVED_FOR_PLATFORM_USE_INTERRUPT_CAUSE,
	};

	enum Exception {
		INSTRUCTION_ADDRESS_MISALIGNED_EXCEPTION_CAUSE,
		INSTRUCTION_ACCESS_FAULT_EXCEPTION_CAUSE,
		ILLEGAL_INSTRUCTION_EXCEPTION_CAUSE,
		BREAKPOINT_EXCEPTION_CAUSE,
		LOAD_ADDRESS_MISALIGNED_EXCEPTION_CAUSE,
		LOAD_ACCESS_FAULT_EXCEPTION_CAUSE,
		STORE_AMO_ADDRESS_MISALIGNED_EXCEPTION_CAUSE,
		STORE_AMO_ACCESS_FAULT_EXCEPTION_CAUSE,
		ENVIRONMENT_CALL_FROM_U_MODE_EXCEPTION_CAUSE,
		ENVIRONMENT_CALL_FROM_S_MODE_EXCEPTION_CAUSE,
		RESERVED_EXCEPTION_CAUSE = 10,
		ENVIRONMENT_CALL_FROM_M_MODE_EXCEPTION_CAUSE,
		INSTRUCTION_PAGE_FAULT_EXCEPTION_CAUSE,
		LOAD_PAGE_FAULT_EXCEPTION_CAUSE,
		RESERVED_FOR_FUTURE_STANDARD_USE_EXCEPTION_CAUSE = 14,
		STORE_AMO_PAGE_FAULT_EXCEPTION_CAUSE,
		//RESERVED_FOR_FUTURE_STANDARD_USE_EXCEPTION_CAUSE_BASE = 16,
		//RESERVED_FOR_CUSTOM_USE_EXCEPTION_CAUSE_BASE = 24,
		//RESERVED_FOR_FUTURE_STANDARD_USE_EXCEPTION_CAUSE_BASE = 32,
		//RESERVED_FOR_CUSTOM_USE_EXCEPTION_CAUSE_BASE = 48,
		//RESERVED_FOR_FUTURE_STANDARD_USE_EXCEPTION_CAUSE_BASE = 64,
	};

	virtual void raise_exception(uint32_t cause) = 0;
	virtual void raise_interrupt(uint32_t cause) = 0;
};
#endif //INC_CPU_INTERFACE_H_
